export default {
  login: 'john-empuerto',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/jaanreymond',
  html_url: 'https://github.com/jaanreymond',
  followers_url: 'https://api.github.com/users/jaanreymond/followers',
  following_url:
    'https://api.github.com/users/jaanreymond/following{/other_user}',
  gists_url: 'https://api.github.com/users/jaanreymond/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/jaanreymond/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/jaanreymond/subscriptions',
  organizations_url: 'https://api.github.com/users/jaanreymond/orgs',
  repos_url: 'https://api.github.com/users/jjaanreymond/repos',
  events_url: 'https://api.github.com/users/jaanreymond/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/jaanreymond/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Empuerto',
  company: 'iEmpuerto',
  blog: 'www.johnempuerto.com',
  location: 'Cebu, Philippines',
  email: null,
  hireable: null,
  bio: 'CEO of iEmpuerto',
  twitter_username: 'john_empuerto',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
